events {
    worker_connections 1024;
}

http {
    server {
        listen 80 default_server;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log debug;

        # Прокси для backend API
        location /api/ {
            proxy_pass http://backend:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Статические файлы (например, изображения, CSS)
        location /content/ {
            root /var/www;
        }

        # SPA фронт
        location / {
            root /var/www;
            index index.html;
            try_files $uri /index.html;
        }
    }
}