#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER "$DB_USER" PASSWORD '$DB_PASSWORD';
  CREATE DATABASE films;
  GRANT ALL PRIVILEGES ON DATABASE films TO "$DB_USER";
EOSQL